sudo: required

dist: trusty

services:
  - docker

language: node_js

node_js:
  - 9

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn report-cov

before_deploy:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
  skip_cleanup: true
  provider: script
  script: deploy-docker.sh
  on:
    branch: master


